#+HUGO_BASE_DIR: ~/repo/everclassic
#+HUGO_SECTION: posts/2025
#+HUGO_AUTO_SET_LASTMOD: t
#+date: <2025-11-09 Sun 19:57>
#+title:トランス音楽は全てを捨てて自由になる踊り念仏！AVA NIGHT TOKYOにいってきた
#+HUGO_CATEGORIES: EDM
#+HUGO_TAGS: trance

先週大好きになった曲が、Xijaro & Pitchの Stars Collide. 

[[https://www.youtube.com/watch?v=J4Qa7pMVPL0][Somna & Jennifer Rene - Stars Collide (XiJaro & Pitch Remix) - YouTube]]

無限ループしてききまくっていた. すると、そもそもこれがRemixであり原曲があることに気づいた. そしてその人はなんと今週日本にやってくるらしい！なんだよその偶然の奇跡は！いくっきゃないじゃないか！！ということで、AVA NIGHT TOKYO2025にいってきた. 正直、だんだん老齢の身体にはオールナイトのイベントがキツくていかない予定だった. 

* 歌舞伎町・王城ビルという異空間

新宿歌舞伎町、王城ビル、噂にはきいていたがはじめていった. 古いビルを建物まるごとクラブにした感じだ. 廃墟感ただよう. 大きなクラブというわけではないので、柵で囲まれたむこうで同じ高さでDJをているので、いつも以上に臨場感がある. 最近DJコントローラを買ったばかりなので、手元が見えたのがよかった.

そんなにお客さんは多くない. うーん、やはりトランス音楽のマーケットの狭さを感じてしまう. わたしはこのジャンルは好きだし、もっとみんな聞いて欲しいと思うものの認知度は低い.

AVA RecordingsはTranceのなかでもUplifting Tranceだから好きだ. Andy Moor/Somna/Rinalyのノンストップトランス. SomnaさんのDJの一番最後でお目当ての Stars Collideがかかって最高だった(ほっとした).

* 旋律をつかんで踊る感覚はリズムとは異なる

だんだん踊り方が分かってきた. 大事なのは曲の展開を予測することだ. トランスはテンプレ的なのでなれれば波が分かってくる. それにあわせてブレイクとドロップ、ビルドアップを待ち構えること. これがポイント.

今回、旋律に乗るということをより意識した. ブレイクの部分はドラムの縦のリズムをつかむ感覚ではなぐ゛メロディーに乗る感覚が必要だが、リズムとメロディーの使い方は音楽の感じ方がずいぶん異なる. この２つをスムーズに切り替える工夫が必要. このへんはクラシック鑑賞の感覚が生きるし、トランスが好きなのは甘美な旋律への陶酔があるからだ.

ただ気になるのは、ライブだとキックの音圧が強いことによってメロディーが埋もれてしまう. クラシック音楽だと、やたらと音楽の立体性へのこだわりがあるが、どうもクラブのライブだとそのへんが雑すぎる気がする. とはいえ、それはたとえばYoutubeとかできくとそこまでバランスが崩れてない. ライブは音圧を浴びにいく細かい綾は録音で楽しむ、このへんの割り切りは必要なのかも.

* 手放す、手放す、手放す、そしてトランス

ライブでのトランス音楽鑑賞においては、受動的にきくよりも積極的にトランスしてエクスタシーしていく態度が重要. このあたり、瞑想ににている. 瞑想は呼吸に乗ることでどんどん瞑想トランスに突入していく、トランス音楽は音に乗ることでどんどんエクスタシーエクスタシートランスに突入していく. Andy MoorさんのときにTake me Awayがかかってそれを思った. ここではないどこかとは、トランスっぽい.

[[https://www.youtube.com/watch?v=faHomJimjLc][4 Strings - Take Me Away - YouTube]]

Upliftingトランスはとても気分を高揚させるので、ここであえて日頃のうつな気分を思い出してみる. すると、ネガティブとポジティブの混合感情によって、よりいっそう感動が高まる. 嫌な事は手放す、踊りで手放す、わたしにとって、トランス音楽は踊り念仏なんだ. 王城ビルで往生しました. 捨聖に憧れる.

* See Also

- [[https://note.com/djneco/n/na76561d16028][トランスレジェンドAndy Moorをはじめ、20組以上のDJ達が3フロアに渡って新宿で展開するトランスの祭典AVA NIGHT TOKYO 2025｜DJ NECO]]

