#+HUGO_BASE_DIR: ~/repo/everclassic
#+HUGO_SECTION: posts/2025
#+HUGO_AUTO_SET_LASTMOD: t
#+date: <2025-01-12>
#+title:はじめて渋谷のクラブWOMBでトランスミュージックをきいてきた
#+HUGO_CATEGORIES: EDM
#+HUGO_TAGS: Trance クラブ WOMB

トランスミュージックはもう数年間ずっと好きだけど、クラブがネクラ無職ひきこもりおじさんには敷居が高すぎて若干諦めていたものの、25年の目標ひいては人生の目標のひとつであるクラブでトランスミュージックをきくという夢を叶えるために、単独ひとりで渋谷のクラブにいってきた!

そもそも諦めていた理由は基本的にクラブは23時頃から始発にかけてのイベントなので、その時点で夜遊びが怖くてできない自分には無理だった. というより、生活リズムが5時におきて仰天坐禅なので、そのサイクルを崩したくなかった. ただ、今回のイベントはTrance Essencialという、16時から-21時までのよい子にもやさしい時間帯のイベントなので参加した. トランス基礎講座. 

* クラブについて

会場はWOMB渋谷という有名な箱なのだが、今回の会場はメインホールではなく小さなサブホール. まずホテル街にクラブがあるのでビビる. しかし、わたしは実は学生のころにこの辺に入り浸っていた. 渋谷にはライオンという昭和元年からあるクラシック名曲喫茶があり、とてもよく通った. まさか若いときにクラシック名曲喫茶に通って、おっさんになってクラブとか、どう考えても逆だろう. 

WOMBには16時前につくと外で人だかりができていた. 期待高まる. しばらく外で待っていると中から声がかかりぞろぞろ中にみんな入っていって列に並ぶ. 列の先頭まできたらかわいいアイドル4人の写真が並べられていて、なにか違うことに気づいた. 同時開催の地下アイドルライブの物販の列だった. どうりでダサいオタクばかりだったとダサいおっさんは思った. 

そして目的のトランスパーティーは16時開演なはずなのにそもそも16時過ぎても開場すらしない. さらに15分後にやっと開演した. なんだこのテキトーさは！やっと中に入ると、フロアは暗くてすでに怖い. お客はわたしを含めて5人. のちに気づくが、開演しても2時間くらいはそもそも人が集まらない. 

わたしはなにも知らずに、会場に入るや否やトマトジュースを一気飲みして、フロアの真ん中で一人で踊りまくった！まったく空気を読めない初心者丸出しだったかもしれない. 30分くらいして踊っている人が自分しかいないことに気づきこれはなにかおかしいと思ったが、もう怖くて後ろを振り返れなかった. 振り返ると『お前なに調子のってキモいダンスしてんだよ？！』と怖い人たちに暗闇に連れ込まれてこのやろバカやろクソやろとボコボコに殴られて全財産とられてクラブから叩き出される気がしたので. そんな怖い場所というのがはじめての印象. 

しかし、客がスカスカな状態でDJが一生懸命プレイするのは、なんだか落語の寄席を思い出してああ芸人文化はいいなと思う. クラブは平日昼間の寄席と同じだ. 前座二つ目ではなく真打ちがでる時間からお客が集まってくる. 実際に3人目のDJあたりから人が増えた. そして、少ないからこそ、落語は一人一人の笑いにかかっている！という川柳川柳師匠のよくやった会場いじりのように、わたしがこのDJプレイを一身に受け取らねばと思った. 

若い人ばかりでおっさんが浮いたらどうしようとずっと不安だったがそれは取り越し苦労. 客層は外国人とおっさんが多かった. 若者はむしろすくない. ただASOTのYoutubeみてても、老若男女がみんなトランスで盛り上がっている雰囲気が好きなので、若すぎない雰囲気はよかった. ただこれは深夜ではないイベントなので、深夜イベントがどうなのかは不明. 

* 音楽について

やはり音圧はYoutubeとは違う、生の醍醐味. むしろこれがすべて. 会場が悪いのか、音のバランスが悪い. しばしば音が大きすぎて音割れするような印象を受ける. 歌詞もなにをいっているのか聞き取ることがむずかしい. しかし、それはクラシック音楽コンサートになれすぎたクラヲタの感想だけど、そもそもクラシックとトランスでは勝負するポイントが違う. 繊細さや音のハーモニーはクラシック音楽においては大事だけど、クラブは音圧がすべて的なところがある. 同じ基準で考えてもしかたがない. 

一番のクラブにおけるトランス鑑賞は、自分がリズムに乗って踊る、という身体性なのだ. クラシック音楽はいすに座ってジッときくが、クラブでは踊って疲れる. ここが違うし、音を浴びながら踊るというのがライブでしか味わえない体験. 許光俊の生演奏以外はウソという言葉が脳裏をよぎる. クラシックもそうだった、高校2年のときにハマってから3年間、コンサートにいったことはなかったけどひたすら図書館のCDをききまくった. 3年のCD生活をへていざ生演奏をきいたら、ああクラシックコンサートじゃないと今までの鑑賞はウソだなと思った. 20年の歳月をへて、クラブミュージックも同じ感想を得る. 生以外嘘なのだ. 

踊りに関して、そもそもどうやって踊ればいいのかわからなかったけど、とりあえずピョンピョン飛び跳ねた. しかし、自分でも驚くが、よく長い間踊りつづけれるものだ. これは日々のチョコザップハードテクノトレッドミルのトレーニングのおかげにほかならない. むしろ、盛り上がるところ以外は心拍数が100BPM程度だが、チョコザップだと120から140を狙って走り込むので、心拍数的にはヌルい動作をしている. 

* DJプレイについて

はじめのYOSHIMASAさんは、そもそもイベントの仕掛け人だから前座でもなんでもなくベテラン. ただ、王道トランスというよりはハードトランスな印象. 気持ちいいシンセというよりは硬いリズムを重視. そもそもトランスなのかすらわからなかった. 

2番目ndkさん3番目TORUKKさんのDJから、ようやくよく知っているシンセが降り注ぐビルドアップ、ブレイク、ドロップのサイクルのDJになった. とくに3番目の人はとてもオーソドックスなクラシックトランスなのでわたしはこれが一番好き. サイケもハードもいいんたけど、わたしは普通のトランスを聞きにきたので、TORUKKさんのプレイが一番よい. 

4番目のふもっふさんから人が一気に増えた. 追っかけみたいなオタク男子もおおかった印象. ふもっふさんはトランスでもいろんなスタイルを織り交ぜている印象だが、ひとつ疑問に思ったのはビルドアップからブレイクしてそのあと次の曲につなげる. なんだか延々に上り坂を上がり上がりでビルドアップ、ブレイク、再ビルドアップ、ドロップの流れとちょっと違うところが違和感を感じた. こういうのはまたそういうDJのテクニックなのだろうか？わからないが、そもそもそういう観点であたらしい発見があるところも面白い. 

5番目のDJ34さん、このイベントはDJ34さんのバースデーパーティー的なこともあり、ここが山場であり、人も一番多く盛り上がった. わたしが嬉しかったのは、きいたことがある曲ばかりがかかったこと. それまでそもそもきいたことがない曲ばかりだったので、あれこれはトランス？ハードテクノ？サイケ？みたいな問いを繰り替えしていたが、なんかようやくこれを聞くためにきたんだ！という感動があった. 

結局20時半すぎに会場をあとにしたが、4時間踊り続けた. これは素人まるだしの感じて、玄人はたぶん18時すぎから集まって3時間くらい滞在するのが正解. わたしも次回があればそうしよう. 

