#+HUGO_BASE_DIR: ~/repo/everclassic
#+HUGO_SECTION: posts/2025
#+HUGO_AUTO_SET_LASTMOD: t
#+date: <2025-01-25 Sat 00:10>
#+title:ブラームスの音楽に合掌して祈り美にして崇高なるものに身を委ねた/トゥガン・ソヒエフ/N響
#+HUGO_CATEGORIES: クラシック音楽
#+HUGO_TAGS: 仏教 N響 コンサート

N響コンサートにいってきた. E席3000円. E席は音は悪い、音が届かないんだ. テレビで聴いたほうがマシな気分. ただ、それは認知の問題で克服できる問題. ほとんど目をつむって、舞台の演奏はみなかった. 

ただ、今日のお目当てはソヒエフさん. しばらくクラシック音楽をきくことから離れていたから、再び生演奏が聴けることがほんとうに感慨深い. 大学の卒業旅行でパック旅行でフランスパリにいったが、ホテルについた瞬間に集団行動から外れてトゥールーズ・キャピトル管弦楽団のコンサート会場に突っ込んだときの指揮者がソヒエフさん. 当時の日記で「かれはまだ33歳なのにすごい!」とかかれていた. 今の彼は頭の禿げ上がった巨匠になりわたしもおっさんになっていた. 本当に感慨深い... そして卒業旅行のお金を一生に一度のお願いで親から借りたのをまだ返済していないこともついでに思い出した. 

また後から知ったのだが、N響コンマスの篠崎史紀さんの引退コンサートらしい. 衝撃だ、昔からずっとこの人が指揮者の隣にいた. ブラームス交響曲1番とはさらによい. わたしの中でN響の音はドイツ的な重い響きが魅力、ブラームスに最適だと思っている. 

ストラヴィンスキー組曲「プルチネッラ」、たぶんはじめて聴く曲. バロック音楽を新進気鋭モダン音楽作曲家のストラヴィンスキーがリミックスしました的なやつ. ストラヴィンスキーからみれば200年前の曲を、当時の最先端の音楽で料理した. 今から200年前はベートーヴェンの時代だからそれをテクノリミックスするようなノリか？しかし、バロックと現代音楽はいちおうクラシックなスタイルだから同じ地平線にあるけど、それから100年立った現在は電子音楽がメジャーになり、ずいぶんと音楽シーンは変わった気もする. 

ブラームス交響曲第一番. 大好きな曲だが昔は聴きすぎた曲でもある. 久々に通してきくと、第二楽章でとても感動したことがおもしろい. むかしは第四楽章で感動したものだった. 年を重ねると、味わいが変わるところがクラシックのよいところだ. 第二楽章ですでにハンカチ片手に泣いてた. マロさまの殺人的なヴァイオリンの音色に殺られた. 

クラシック音楽にハマっていた時は、これは宗教だと思っていた. クラシック音楽教である. 第四楽章は、クラシック音楽王道なフィナーレによる救済であり、当時を思いだした. 一方、去年は仏教にがっつりハマり坐禅に明け暮れた. すると今2025年のわたしは、キリスト教的な信じるものは救われる的な宗教と、あらゆるものは関係性の中で生成消滅するなにかという仏教、２つを比べざるをえない. 

第四楽章のメロディーの提示部分、わたしは合掌をして目をつむり、この世でもっとも美しい旋律の登場を息をひそめて待っていた. これは昔からの無意識のクセなのか、気づいたらそんな感じで聴いていたのだが、祈りの態度そのものだった. すぐ泣くのも昔からのクセなので仕方がない. 

わたしは神は信じてないし、そのため仏教も仏さまへの信仰はまだうまく自分の中で消化できてない. 坐禅をしていて未だつかめない感覚が、無常に寄り添う感覚. どうしても無常が単なる虚ろに思えてしまう. 日常生活でつらいとき、キリスト教とか浄土宗のように祈りの信仰にすがれることがとても羨ましいなと思う. 最近では、結城浩さんのブログを読んでそう思った. 坐禅にはその感覚がどうしてももてない. 経験が浅いだけなのか、曹洞宗にも帰家穏坐という言葉があるが、どうしても感覚がつかめない. すがれない、祈れない、虚無だけがある. 

そういう悩みを抱えていた去年の経験から、久しぶりにクラシックコンサートに出向き、気づいたら合掌をしてブラームスの音楽に涙を流しながら祈りを捧げている自分がおもしろい. 自我を気づきで滅尽する仏教と、自我を大いなるなにかに委ねて一体化するクラシック音楽の方向性は真逆であるが、共通で扱っている課題は自我をどうやって滅尽するかというところ.

* Infos

- 第2029回 定期公演 Cプログラム
- ストラヴィンスキー／組曲「プルチネッラ」
- ブラームス: 交響曲第1番ハ短調 Op.68
- NHK交響楽団
- トゥガン・ソヒエフ

* Refs

- https://www.nhkso.or.jp/concert/202501C.html?pdate=20250124
- [[https://www.hyuki.com/writing/inori][祈りの心がけ - 結城浩]]
