#+HUGO_BASE_DIR: ~/repo/everclassic
#+HUGO_SECTION: posts/2025
#+HUGO_AUTO_SET_LASTMOD: t
#+date: <2025-03-01>
#+title:Paul van Dykをきいて人生初めてオールナイトパーリナイした
#+HUGO_CATEGORIES: EDM
#+HUGO_TAGS: Trance クラブ ZeroTokyo

トランスの帝王, Paul van Dykが来日ということで人生初めてナイトクラブへ行った. 新宿歌舞伎町ZeroTokyo. 前回は日中イベントでした. 

* 深夜オールがおっさんにはきつい

いろいろと感想はかきたいものの、まず悪いことは、おっさんには徹夜オールがきつい、したがって翌日の今は生気がない. そして、公演が終わって6時間くらいずっと耳鳴りが続いた. とりあえず気力を振り絞って覚えていることだけ文章にdumpしたい. 

そもそも3/1の2時からとは、2/28の金曜が公演かと思ったら、土曜だった. 土日は両方とももくもく会の予定をいれていたので、計画狂わせだ... 

土曜日は朝多めに寝ようとしたが結局眠れず、22時に家をでる前に2時間仮眠を試みるが、眠れず. 結局3時間以上ふとんのなかでじっとしていて、それでも横になっているだけで睡眠の効果はあるんだよという誰かの助言を信じた. クラブが深夜だと、通いなれている人はどうやって睡眠を調整しているのかわからない. 学生カラオケオールの体力がないから、戦略的に睡眠をとらないとつらい. 

* 耳鳴り問題が怖い

耳鳴り問題がとても怖い. そもそも月曜日にMartin garixが耳鳴りに悩んでいる記事をたまたま読んで怖くなり、Loopのライブ用耳栓をネットで購入. Paul van dyk登場まではずっとイヤホンつけてたのだが、それでも閉演あとに耳鳴りが6時間は続いた. これも工夫で改善できるのだろうか？とくに中心から左によった位置によくいたので、左耳の耳鳴りがひどい. また、今日はなるべく前の方でPaul van Dykをききたいと思って、途中でホールを抜けてトイレ休憩やドリンクを飲むこともなかった. 普通は1時間くらいきいたら、10分くらい耳を休めないといけないのかも. [fn:1]

* ZEROTOKYOが外国人ばかりだった

ナイトクラブ初なのでZEROTOKYOが特別かもしれないが、とにかく外国人が多い. なんなら途中まわり全部外国人だった. 日本人のわたしは身長が低いので、突然目の前に高身長の人間が立たれると、ああもう見えないとなる. しかし、日本人女性とか、もっと慎重が低くてかわいそうだ. 場合によっては背伸びしても見えないのでは？

Paul van Dykの出番になるとぎゅうぎゅう満員状態で、踊るどころか自分のパーソナルスペースなかった. そのあとのRinalyさんだと、一気に人がいなくなったけど. 彼は観光客だからそのへんのホテルに宿泊しているのだろうか？そもそも歌舞伎町が外国人旅行客がおおいともきき、ZEROTOKYOは観光ガイドおすすめスポットなのかも. 

* 最先端メディアアートを体験した気分

メインフロア開口一番はSeimeiさん. まあまあ王道のトランス？テクノ? どっちだろう. しかし、事前にPaul van Dykのインタビューをきいていて、そもそもテクノトランスの分類なんてしなくていいんだということきいていたので、まあいいかと思った. [fn:2]

驚いたのは二番目のJun Inagawaさん. はじまってすぐに凄まじいノイズが流れたのだが、そのノイズの音響を通じた身体への振動が驚いた. そして音を自在に操ることで、音を媒介して身体を振動させることに驚いた. これはZEROTOKYOの音響設備があればこその音響体験. さらにはVJによる視覚的な映像. 

ここには間違いなく、メディアアートの最先端があり、それを感じた. 

最先端？わたしはそこまで情報を集めていたり体験がないので、最先端かはわからない. わたしの舞台芸術体験はオペラしかない. そして、若いころからずっとクラシック音楽/オペラ通いだったけれども、25歳くらいからその古典から新しいことが生まれないことがだんだん嫌になってきた. だからこそ別のジャンルの音楽を知りたいと思った結果、今ここにきた. たしかにオペラは前衛的な演出だとデジタルアート的なものもあるが、そういう古典をなんとか現代に飾ろうとかではなく、これが現在の芸術だ！といわんばかりのテクノロジーをつかったアートにわたしは興奮したのだ. 

そして、ドイツの偉大な芸術は、古汚い骨董品のようなベートーヴェンブラームスワーグナーではなく、テクノであり、トランスであり、ジャーマントランスの帝王、Paul van Dykの音楽を今、きくのだ. といわたしの妄想. 

* Paul van Dyk降臨

そしてフロアで0時から待つこと2時間、ついに3番目として大看板、Paul van Dyk降臨. フロア込みすぎておしくらまんじゅう. 踊るとかじゃなかった. 

はじめの数回のビルドアップブレイクの波をつくって会場をどんどんもりあげていく、拳をつきあげてフロアバンカーするようなパフォーマンスもかっこいい、前のほうで観れてよかった. 

わたしのトランスの入り口はArmin van buurenやダッチトランスだけど、それとは似ているようだが異なるもうひとつの音楽、ジャーマントランスを感じた. まちがっているかもしれないがあえて言葉にしてみると、よりドンドンというキックが強め、派手さというよりはいぶし銀のような黒光りする音色、抑えるところは抑えつつ爆発させるところは爆発させるニュアンスの調整. これはPaul van Dykの芸風なのかもしれない、ときおり人差し指をつかって上を見上げ、聴衆の意識を一点に集中させて、ふっと力を抜いて、ガーンとぶちかます、うぉーっと会場がうなる、この会場のテンションを仕草と音で操るのが、芸だと思った. 

今人生はじめて本当のトランスをきいているのだなと思った. 本当のというのは、音圧を身体で感じながら、ナイトクラブの深夜2時からの、熱狂するクラブでのトランスという意味. 今ままでもずっとYoutubeではきいてきたんだけど、生以外は試供品であり、ウソなのだ、と思った. まあ耳鳴り問題と体力があって、ここにくることのハードルが高いけど... 

* Footnotes

[fn:1] 
[[https://iflyer.tv/article/2025/02/23/martingarrix-tinnitus/][iFLYER: 世界トップDJのMartin Garrix (マーティン・ギャリックス) 、耳鳴りの悩みについてポッドキャストで告白…「常にビープ音が聞こえている」]], キャリア初期に耳栓をせず、スタジオで大音量のお学を聴きながら長い時間を過ごしたことで発症した. 音楽業界の多くの DJ が耳を保護せずに大音量の音楽に晒されているため、耳鳴りに苦しんでいることを強調した。しかし、この耳鳴りは DJ やプロデューサーだけに限った問題ではない。フェスティバルやレイヴの参加者も同じように危険に晒されている。Martin Garrix のこの率直な発言は、長期的な聴覚障害を回避するためには、大音量の中では面倒臭がらず耳栓をつけるべきである.

[fn:2] [[https://www.youtube.com/watch?v=Mw07WHte9zg&t=2800s&ab_channel=WillClarke][Paul Van Dyk - The Don Of Trance & One Of The Longest Residents on Ibiza - YouTube]], t36あたりから.
