#+HUGO_BASE_DIR: ~/repo/everclassic
#+date: <2026-02-08>
#+title:大人になっても感受性は問題なかった、ちゃんと泣いて歯もガクガクした - フィリップ・ジョルダン指揮/N響/ワーグナー神々のたそがれ
#+HUGO_CATEGORIES: クラシック音楽
#+EXPORT_DESCRIPTION: NHK交響楽団/指揮フィリップ・ジョルダン/シューマン交響曲 第3番/ワーグナー楽劇「神々のたそがれ」
#+HUGO_TAGS: コンサート N響 ワーグナー シューマン

1年ぶりのN響コンサート. EverClassicのブログをリニューアルしたら久しぶりにクラシック音楽コンサートにもいきたくなったので. 

* 初心者マインドで音楽を楽しめるようになった

前回の反省を活かし、E席はやってD席にしたい. 今回はあたり. 2Fの奥の席なので、ここは音がちゃんと届く席. さらに壁際はより音が聞こえやすい. ここはコスパがいい席. ただし、Webからの予約では席の指定をした記憶はない. 運次第？

指揮者のフィリップ・ジョルダン、知らない人だったが、もうあまり以前のように指揮者のタッチによる演奏の良し悪しにこだわる心もない初心者マインドで音楽を楽しめるようになった. ちょっとテンポが速いか？もうちょっとゆっくりの方がいいかな、そう思うのは歳のせいだろうか？弱音のバイオリンがよい. 体感に訴えてくる. チェロの美音にお耳が弱い. 

浪人生のときは1日中ワーグナーばかり聞いていたので、モチーフの記憶は微かに残っていたようだ. どこをきいても懐かしかった. ワーグナーとか、最後に生できいたのは15年前なんじゃないかな？あんなに中毒のようにきいたワーグナーは、いつになっても感動できる. やはり大編成オケはワーグナーの魅力だ. ハープも6台？ティンパニは2台。しかしワーグナーだとしても音圧の弱さを感じてしまうのは、昨今の電子音楽の音圧に耳が壊れたか?

* 大人になっても感受性は問題なかった、いや若いときよりも高まった

シューマンの第４楽章にしろ、ワーグナーのラインの旅にしろ、ちゃんと涙が出て感動できてよかった. 

わかいときは、今が人生のうちで一番感受性が高いときだか、今のうちに一番感動してかなければ！と思い込んでいた. きっと大人になればなるほどに、音楽に対して感動しなくなるのだろうと. 

価格帯 x 感受性 / 年齢 = 感動

この方程式が成り立つならば、感受性を高めれば安い席でも感動できるはず. しかし、そんなことはなかったようだ. いやむしろ、久しぶりのコンサート効果もあったのか、より一層いぜんよりも感動できた. 

感動すると歯がガチガチ揺れ始めるのはどうしてなんだろうか？感動すると鳥肌が立つ、いわゆるフリッソンと歯のガチガチは関係なさそうだがむしろ涙に関連がありそうだ. フリッソンと涙現象の関係は深掘りしたい. これらは別の生理反応感動で幸せで泣くとはどういうことだろう？

* N響は100年後もN響なのか？

NHKホールにはN響100年の歴史を讃える看板があった. 100年は継続したが、今後100年はどうなんだろうと心配になる. テレビメディアに執着してはあと100年は無理だ. 私自身、もう15年以上自宅にテレビがない生活たが、テレビがもうオールドメディアにしか感じない. 

結局N響が日本一なのは資金力な気もするが、収入源がどんどんなくなっていくと、いくら個々人の努力ではどうにもならない気もする. 

* 第2057回 定期公演 Aプログラム NHK交響楽団

[[https://www.nhkso.or.jp/concert/202602A.html?pdate=20260207][第2057回 定期公演 Aプログラム | NHK交響楽団]]

- 指揮: フィリップ・ジョルダン
- ソプラノ: タマラ・ウィルソン

---

- シューマン／交響曲 第3番 変ホ長調 作品97「ライン」
- ワーグナー／楽劇「神々のたそがれ」 ─「ジークフリートのラインの旅」 「ジークフリートの葬送行進曲」 「ブリュンヒルデの自己犠牲」

