#+HUGO_BASE_DIR: ~/repo/everclassic
#+date: <2026-03-22 Sun 17:23>
#+HUGO_CATEGORIES: EDM
#+title: サイケトランス初体験、SonicAcademyの先生Protocultureがやってきた！
#+HUGO_TAGS: クラブ Trance ZeroTokyo PsyTrance

* SonicAcademyの先生がやってきた！

DTMを2年前からはじめた. 当時Linuxをメインにつかっていたので、Linixでも動くDAWを探したらBitwig StudioだったのでこれをDAWに選んだ. そして、Bitwig Studioでトランスを製作するためのチュートリアルを探したところ、Sonic Academyの Protocultureさんの動画が唯一の選択肢だった.[fn:1]

もっとも、チュートリアルはどんなDAWもある程度は学べるが、当時は情弱だったのでそのことを知らなかった. 結果的に、1年間Sonic Academyにして、Protoculture先生のBitwig Studio使い方講座、そしてProgressive Tranceのチュートリアルを半年以上かけてみていた. なんと、その先生がやってくるのだ. 

正直、前日は一泊二日で家族でお墓参りのため旅行していたので参加を直前まで悩んでいた. そして、実際旅行でお腹を壊してほぼ当日は体調不良. そのため、イベントまでの数時間は横になっていたが結局眠れずに単なるシャバッサナ. そして、朝食からなにもたべない断食行でイベント参加. 到着しても、水だけでアルコール無しで吐きそうなので、後方の隅のほうでピークタイムまで体力温存していた. 

* そもそもサイケトランスのイベント参加が初参加

そもそもだが、サイケトランスのイベントに参加することが初めてだ. 動画でみるかぎり、野外サイケフェスの映像は謎の踊りをする人たちで狂っていたが、今夜も同様なフロアでありとても面白かった. あの、踏むようなステップはなんというのだろうか？クラブでの踊り方に正解はなぽものの、サイケトランスのジャンルはなにか独特の動きがある. 

* ヨーガ行者の端くれとしてちょっと気まずい背徳的密教イベントにシビれる

わたしは仏教徒であり、行として座禅をしている. しかしに座禅に打ち込むにつれ、自分がやっていることは、仏教の顔をかぶったヨーガ=心の止滅なのでは？という疑問がずっとあり、その問いを深堀りするためにヨーガについてもいろいろ学んでいる. 

しかし、ヨーガもヨーガで複雑であり、現在流行しているハタヨーガの源流はタントリズム=密教. シヴァ崇拝と仏教が混じったナート派からの分離. そのタントラ仏教はもう初期仏教からかけ離れているため、どうもこれは仏教ではない！と否定しつつもその密教的世界観に憧れたり、ハタヨガをやったりするというダブルバインドがある. 

そもそも仏教とトランスミュージックが最近の第一の関心事だが、あまりにもこの２つの趣味の相性が悪すぎる. この二つの趣味を強引に合体する交差点としてサイケトランスがわたしの中にはある. バタイユ的には禁則を破る背徳に力が沸くという. サイケイベントへの参加にはそういう謎の魅力がある. 

実際、とても興奮したのは、TA-KAさんのDJプレイの後半で仏像がスクリーンに大きく映し出されたこと. そして、最後の曲が、シャーンティ、シャーンティ、シャーンティという有名なサンスクリットのマントラで終わったこと. これに興奮してしまうとは、なんとも背徳的だ！なお、ミャンマーでこれをやると警察に拘束されて僧侶に謝罪が必要？[fn:2]なお、本日はお彼岸. いろいろ問題がある. 

https://youtu.be/BjfQggf_fWI

* 先生、朝マックモーニングプログレじゃないんですか？！

そして、TA-KAさんの次はProtoculute先生. 

毎朝5時におきて、6時からオープンする朝マックでコーヒーを飲んでDTMの勉強を1時間することがわたしの日課だった. 2つのチュートリアルはどちらもProgressive Tranceだったので、こういうのが先生のスタイルだと思い込んでいた. 

そのため、まさかのサイケトランスをバリバリぶっこんできてビックリ仰天した. 先生、プログレトランスじゃないんですか...そもそも動画ではメガネつけたヒゲおやじだったので、メガネなくてヒゲをそった顔が遠くからみたら同一人物にみえなくて、はじめにスマホでProtocultureは2人いるのか？ということを調査した. 

サイケのなかでもモーニングという美メロが多用されるジャンルらしい. わたしは朝マックで毎日モーニングトランスを聞きつづけてきた. 準備万全だな. 

* Protocultureとは人類の起源を遡ること

Protocultureとは、人類学用語. 非ヒト霊長類(サルなど)が学習した行動を次の世代に伝えていく現象を指す. トランスの文脈に結びつけるならば、ホモサピエンス以前＝人類のルーツへの回帰という意味がありそうだ. 

ちょうど、最近発売された宮台式人類学の書籍を毎日読んでいる. [fn:3]今回も行き帰りの電車で読んでいた. 内容の一部は、社会学から社会を分析するのではなく、社会学以前の人類学から共同体を考えてみよというもの. 副題が前提を遡る思考なのだが、遡っていく根拠として進化学からアイデアを得た考察が多い. 

この音楽による集団的トランス状態というのは、なんとも社会以前の人類に回帰するような活動だ. 踊っているとき、いつもならばうつな反芻思考で苦しいものが晴れるのが好きだ. そこでは言語がない. 

この書籍は分厚くて難しくていまいち理解が難しいのだが、この書籍を読み進めていると、言語を越えた体験とか、自分を越えた畏怖とか、人間がゲノム的に刻みつけられた本能に対する関心が最近高い. それば一方で、AIによってこれから30年で歴史的な革命が起こるので、この苦しい現代社会以前に興味が向く. 

あまり詳しく言葉で表現できるわけではないが、トランス体験という言葉にならない体験や感動は、書籍でいう劣化した「育ちの悪い」わたしにとって今さらながら学びの材料となっている. 

* Footnotes

[fn:1] [[https://www.youtube.com/watch?v=9XZ36vlb7wQ][Trance Takeover! - YouTube]]

[fn:2] [[https://www.sankei.com/article/20250913-ZE6CMPXV4ZKU3GEE2NCWLVH23M/][仏教冒瀆疑いでミャンマーの人気女性DJを拘束　お経使った曲、SNS「失礼極まりない」 - 産経ニュース]]

[fn:3] [[https://www.chikumashobo.co.jp/product/9784480077356/][『宮台式人類学』宮台　真司 | 筑摩書房]]
