#+HUGO_BASE_DIR: ~/repo/everclassic
#+HUGO_SECTION: posts/2024
#+HUGO_AUTO_SET_LASTMOD: t
#+date: <2024-09-14 Sat 09:13>
#+title:Ultra Japan 2024でついにテクノ/トランスとArmin van Buurenを生できいた
#+HUGO_CATEGORIES: EDM
#+HUGO_TAGS: Trance Techno フェス

トランスミュージックを本格的にききはじめたのは記憶では３年前. きっかけはASOTだった気がする. 2022の１月あたりの年末年始にASOTをウーバー待機中にたくさんきいた思い出. あれから2年ちょっと, ついにトランスミュージックを生できくことができた.

イベント当日の朝は町田の坐禅会に参加. そのためいつもどおり５時に起きたのだが後々若干後悔した. 夜遅くなったので午後に眠くなった.

* 初めてのテクノ体験

会場についてまず聴いたのが, Risa Taniguchiのテクノ. これが初めてライブできくテクノミュージックだ. まず音圧に驚いた. そしてすぐ理解したことはクラブミュージックはそもそもYoutubeとかできくものではなく, 音圧を身体で踊るものだった. 体験しないとなにもわからなかった. とくに, Risa Taniguchiさんの音楽がUKベースミュージックに影響を受けていてことさらそこは重視されたプレイだからだと思う.

[[https://www.youtube.com/watch?v=x-iT7zVxvwg][RISA TANIGUCHI // ULTRA JAPAN 2024 SEP 14 SATURDAY RESISTANCE STAGE (VJ: H2KGRAPHICS) [HD] - YouTube]]

#+begin_quote
;; https://www.whitelifemag.com/whitecanvas01/

体にくる振動だったり、内臓が動くか動かないかみたいな。そこで楽しむ音楽というんですかね。低音が効いてて、楽しみ方としても、みんなで揃ってハンズアップして仲良く踊るというよりも、自分の世界に浸りながらガン踊りしたくなるようなタイプのもの
#+end_quote

クラシック音楽にも生以外ウソみたいなドグマがあり, それを思い出した. たしかに今となってはクラシックの交響曲をCDできくきにはなかなかならない. 好きな曲ならそれもありだが, 知らない曲だとなかなかそういう気分にならない. 

朝に坐禅をしていたからか, テクノミュージックをきくことはもはや坐禅だと思った. 坐禅には心臓の鼓動、呼吸という身体のなかで発生する不随意なリズムを捕まえ, あとはそれに委ねる. 坐禅だとここで仏を持ち出して仏に身を委ねるという. それは自分の意志ではなく勝手に起こるものだ. このようなものを自我とは離れて観察する. まさにテクノミュージックをきくということは云為の坐禅と同じだ. クラブミュージックの場合, 音圧によって身体が反応する, それは呼吸や脈拍よりも高速であるものの原理は同じ. それは自分でコントロールするものではない. 自分が踊るのではなく, 自我を手放して音にゆだねて音圧によって操り人形のように踊らされるのだ. また反復するリズムによって定力が高まり, いわゆるゾーンに突入すると卓球の珠が止まってみえるように？時間感覚が歪んだ世界に突入する. 坐禅は緩やかなリズムでテクノは高速なリズム, しかしそれは物理的な時間感覚とは違う. 

* トランスミュージックでもカタルシス体験はできる

次に感動したのは「みんなのきもち」という２人組のトランスDJ. ネットに情報が少ないのだがYoutubeで公開されている音楽はなかなか普通とは違い事前に衝撃を受けたので楽しみにしていた. そして彼らがトランスミュージック初体験だ. ただ, 私が慣れ親しんだダッチトランスとは違いサイケがかっているのだが, トランスの基本路線である美しいシンセの波や, 静かな部分から盛り上がって最高潮に叩き上げる手法は同じ. しかも彼らの場合, 音が優しくなる部分でアンビエントミュージックっぽくなるのだ. この落差がすごい. 彼らのパフォーマンスの最後でわたしは涙が出たが, これはびっくりした. こういうことは交響曲のフィナーレではよくあることなのだが, まさかトランスミュージックでもこういう音に圧倒され, 自己を超克した畏敬の念による感動のカタルシス体験ができるのか！ということが驚いた. 

この後15時くらいから夕暮れまでもうすでにバテてしまったので夜まで休憩することにしていったん会場を離れてぼーっとしていた. はじめてのウルトラでよくわかってなかった, 開演時間からきて炎天下のなかで踊って, 夜まで体力が持つわけないのだ. 体力を温存するという発想がなかった.

isoknockが評判いいらしかったが体力温存のためにスキップ, おっさんは情けない. Afrojackから参加しようとしたが, その前に寄ったテクノブースでのAnfisa Latyagoのパフォーマンスに魅了されてしまって, あまりに素晴らしくてAfrojackのことを忘れてテクノで踊っていた. Ultra Japanに参加してよかった収穫は, テクノミュージックが一気に好きになったことだ. それはEDMよりも, なんなら楽しみにしていたAfrojackを予定変更してまでテクノがいいと思わせるまで好きになった. 

[[https://www.youtube.com/watch?v=pnTGTOd3wd0][Anfisa Letyago #resistancetokyo #ultrajapan 2024 - YouTube]]

ただそう入ってもAfrojackはぜひ聞きたいと思ったので途中からメインステージへ. 若干後悔したのは人が多すぎてもう前のほうに移動できなかった. 普通の人はisoknockの前からいい場所を狙ってメインステージにいるのだ. Afrojackはもう何年も前からライブは何度もYoutubeで見てきたのでやはり生でみれると嬉しい. とくにAfrojackの横にいるサングラス黒人のアオリ芸が好きなので煽られて感動した. 後ろの方だとパリピが多いので若干びびったがそれでもマッチョ半裸の外人パリピたちがライブ感を演出していた. ライブ映像自体はもうずっとみてきたのでリアルフェスパリピに感動した. アフロジャックの音楽はとにかく盛り上がる. これぞEDMって感じ. ただ, 歌詞付きの部分は盛り上がるのだが音楽だけの部分だと会場のテンションが下がり本人はどう思っているのだろう, だからテクノ名義での活動もはじめたのかな？と邪推してしまった. バカ騒ぎはそれはそれでいいのだがそれだけだと音楽としてどうなんだとおもう. 

* I Live For That Energyと思った

そして最後はArmin van buuren. 正直Ultra japanの今回のDJでAfrojackとArmin以外は普段からきいてなかったので, Armin以外はどうでもよかった. このためにきたんだ！ Ultra Japanの最後がトランスミュージックというのも嬉しい. 毎週ASOTをききArminとトランスを追いかけてきたがXで検索してもいまいちArminの話題もトランスも少なく, だれが日本でトランスミュージックをきいているんだ！と思っていたが, こんなにもArminとトランスを楽しむ人たちがこの場にいることに, ３年間ひたすら一人で毎日トランスミュージックを聞き続けてきたわたしは感動した. Arminのここ数年のライブ映像は全部みてきたので展開はわかっていて, あとはピョンピョン飛び跳ねるだけだった. 

一番感動したのは, ASOT 800 Anthemが流れたこと. ここで泣いた. 正直, Arminとトランスミュージックをきいてきた３年間は, 同時に人生でもっともつらい時期であり, へんな話, 暗い気分を無理やりUplifting tranceによって上げてきた. わたしにとってトランスミュージックはクラブできくものではなく, 暗い室内で一人でふとんをかぶりながら, 祈りのような, 希望の光を求めて, または生きているという生の熱狂を求め, きくようなものだった. トランスミュージックをひたすら毎日きき, トランスミュージックとともに生活してきたこの３年間の感情が音楽とともに 一気に溢れてきた気がした. I Live For That Energyと思った. 

[[https://www.youtube.com/watch?v=VH9fZgX1hJM][ARMIN VAN BUUREN LIVE @ ULTRA JAPAN '24 SATURDAY MAINSTAGE - YouTube]]



